name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    - name: Run tests
      run: npm test
    - name: Generate Allure Report
      if: always()
      run: npm run report
    - name: Upload Allure Report
      if: always()
      uses: allure-reports/allure-github-action@v2
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        reportName: allure-report

